# Generated by Django 3.2 on 2021-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
