# Generated by Django 3.2 on 2021-04-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walker', '0002_alter_walker_rating'),
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.TimeField()),
                ('startloc', models.TextField()),
                ('dog1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dog.dog')),
                ('dog2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dog.dog')),
                ('dog3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dog.dog')),
                ('dog4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dog.dog')),
                ('dog5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dog.dog')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walker.walker')),
            ],
        ),
    ]
