# Generated by Django 3.2 on 2021-04-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='startime',
            field=models.DateTimeField(),
        ),
    ]
